Modified logic for check settings

diff --git a/ssh-bind b/ssh-bind
--- a/ssh-bind
+++ b/ssh-bind
@@ -59,6 +59,13 @@ ssh_bind_count_settings() { # {{{
   ssh_bind_get_settings | $WC_COMMAND -l | $TR_COMMAND -d " "
 } # }}}
 
+ssh_bind_has_settings() { # {{{
+  if [ "$(ssh_bind_count_settings)" == "0" ] ; then
+    echo "Can't find settings for $NAME"
+    exit 3
+  fi
+} # }}}
+
 ssh_bind_get_forwardings() { # {{{
   $GREP_COMMAND -RH "^\($ALLOWED\)" $SETTINGS_PATH | $SED_COMMAND -n "s/$PATTERN/\3 \2/p" | $SORT_COMMAND -u | $SED_COMMAND 's/^:socks:/-D /g' | $SED_COMMAND 's/^:local:/-L /g' | $SED_COMMAND 's/^:remote:/-R /g'
 } # }}}
@@ -89,6 +96,7 @@ ssh_bind_get_ps_list() { # {{{
 
 ssh_bind_start() { #{{{
   ssh_bind_is_root
+  ssh_bind_has_settings
   if [ "$(ssh_bind_count_ps)" == "0" ] ; then
     echo -n "Starting $NAME "
     ssh_bind_get_forwardings | while read FORWARDING ; do
@@ -104,6 +112,7 @@ ssh_bind_start() { #{{{
 
 ssh_bind_stop() { # {{{
   ssh_bind_is_root
+  ssh_bind_has_settings
   if [ "$(ssh_bind_count_ps)" == "0" ] ; then
     echo "$NAME was not started"
   else
@@ -114,6 +123,7 @@ ssh_bind_stop() { # {{{
 } # }}}
 
 ssh_bind_status() { # {{{
+  ssh_bind_has_settings
   if [ "$(ssh_bind_count_ps)" == "0" ] ; then
     echo "$NAME was not started"
   else
@@ -123,6 +133,7 @@ ssh_bind_status() { # {{{
 } # }}}
 
 ssh_bind_settings() { # {{{
+  ssh_bind_has_settings
   ssh_bind_get_forwardings | while read FORWARDING ; do
     ssh_bind_show_command_create_ssh_forwarding "$FORWARDING"
   done
@@ -146,11 +157,6 @@ ssh_bind_help() { # {{{
   echo "  | help     | show this message"
   echo "  $HELP_SEPARATOR"
 } # }}}
-
-if [ "$(ssh_bind_count_settings)" == "0" ] ; then
-  echo "Can't found settings for $NAME"
-  exit 3
-fi
 
 case "$1" in # {{{
   start)
