Added checking if installed SSH Client. (V:1.0.1)

diff --git a/ssh-bind b/ssh-bind
--- a/ssh-bind
+++ b/ssh-bind
@@ -8,12 +8,18 @@ NAME=$(basename $0)
 DESC="SSH-Forwarding of ports"
 AUTHOR="Artem Teleshev"
 VERSION="1.0.1"
+
 SCRIPT=$(readlink -f $0)
 SCRIPT_PATH=$(dirname $SCRIPT)
 SETTINGS_PATH=$(readlink -f "$SCRIPT_PATH/settings")
 
 COMMAND=$(which ssh)
 COMMAND_OPTIONS="-f -n -N"
+
+if [ ! -f $COMMAND ] ; then
+  echo "Can't find SSH Client. You need to install this package."
+  exit 1
+fi
 
 LS_COMMAND=$(which ls)
 PS_COMMAND=$(which ps)
@@ -27,7 +33,7 @@ KILL_COMMAND=$(which kill)
 SORT_COMMAND=$(which sort)
 
 ALLOWED='socks\|local\|remote'
-SETTINGS_PATTERN='\/\?\([^\/]\+\/\)*\([^\:]\+\)*\(.*\)*$'
+PATTERN='^\/\?\([^\/]\+\/\)*\([^\:]\+\)*\(.*\)*$'
 
 STATUS_OK="OK"
 STATUS_ERROR="Error"
@@ -40,7 +46,7 @@ ssh_bind_is_root()  { # {{{
 } # }}}
 
 ssh_bind_get_settings() { # {{{
-  $GREP_COMMAND -RH "^\($ALLOWED\)" $SETTINGS_PATH | $SED_COMMAND -n "s/$SETTINGS_PATTERN/\2/p" | $SORT_COMMAND -u
+  $GREP_COMMAND -RH "^\($ALLOWED\)" $SETTINGS_PATH | $SED_COMMAND -n "s/$PATTERN/\2/p" | $SORT_COMMAND -u
 } # }}}
 
 ssh_bind_count_settings() { # {{{
@@ -48,7 +54,7 @@ ssh_bind_count_settings() { # {{{
 } # }}}
 
 ssh_bind_get_forwardings() { # {{{
-  $GREP_COMMAND -RH "^\($ALLOWED\)" $SETTINGS_PATH | $SED_COMMAND -n "s/$SETTINGS_PATTERN/\3 \2/p" | $SORT_COMMAND -u | $SED_COMMAND 's/^:socks:/-D /g' | $SED_COMMAND 's/^:local:/-L /g' | $SED_COMMAND 's/^:remote:/-R /g'
+  $GREP_COMMAND -RH "^\($ALLOWED\)" $SETTINGS_PATH | $SED_COMMAND -n "s/$PATTERN/\3 \2/p" | $SORT_COMMAND -u | $SED_COMMAND 's/^:socks:/-D /g' | $SED_COMMAND 's/^:local:/-L /g' | $SED_COMMAND 's/^:remote:/-R /g'
 } # }}}
 
 ssh_bind_get_forwardings_pattern() { # {{{
